# Generated by Django 3.1.4 on 2021-01-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20210114_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название списка')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('expare_date', models.DateTimeField(null=True)),
                ('list_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listmodel')),
            ],
            options={
                'verbose_name': 'Элемент списка',
                'verbose_name_plural': 'Элементы списка',
                'unique_together': {('name', 'list_model')},
            },
        ),
    ]
